function write_outputs(result, outputDir, convergence)
%WRITE_OUTPUTS Write language-neutral CSV and JSON products.
arguments
    result struct
    outputDir (1,1) string
    convergence table = table()
end
if ~isfolder(outputDir)
    mkdir(outputDir);
end
p = result.profiles;
harmonics = double(result.case_data.mode.poloidal_harmonics);
profileTable = table( ...
    p.s, p.mass_density_kg_m3, p.iota, p.alfven_speed_m_s, ...
    p.omega_m_rad_s, p.omega_mp1_rad_s, p.coupling_omega2_s2, ...
    p.local_lower_rad_s, p.local_upper_rad_s, ...
    'VariableNames', {'s','mass_density_kg_m3','iota','alfven_speed_m_s', ...
    sprintf('omega_m%d_rad_s', harmonics(1)), sprintf('omega_m%d_rad_s', harmonics(2)), ...
    'coupling_omega2_s2','local_lower_rad_s','local_upper_rad_s'});
writetable(profileTable, fullfile(outputDir, 'profiles_and_continuum.csv'));

modeIndex = (1:numel(result.omega2_s2)).';
eigenTable = table(modeIndex, result.omega2_s2, result.omega_rad_s, result.frequency_hz, result.frequency_khz, result.residual_norms, ...
    'VariableNames', {'mode_index','omega2_s2','omega_rad_s','frequency_hz','frequency_khz','relative_residual'});
writetable(eigenTable, fullfile(outputDir, 'eigenvalues.csv'));

N = numel(p.s);
modeData = p.s;
modeNames = {'s'};
for j = 1:numel(result.omega2_s2)
    modeData = [modeData, result.eigenvectors(1:N,j), result.eigenvectors(N+1:end,j)]; %#ok<AGROW>
    modeNames{end+1} = sprintf('mode_%d_m%d', j, harmonics(1)); %#ok<AGROW>
    modeNames{end+1} = sprintf('mode_%d_m%d', j, harmonics(2)); %#ok<AGROW>
end
writetable(array2table(modeData, 'VariableNames', modeNames), fullfile(outputDir, 'eigenmodes.csv'));
if ~isempty(convergence)
    writetable(convergence, fullfile(outputDir, 'convergence.csv'));
end
metadata = struct( ...
    'case_name', result.case_data.case_name, ...
    'model_status', result.case_data.model.fidelity, ...
    'crossing_iota', p.crossing_iota, ...
    'crossing_s', p.crossing_s, ...
    'crossing_cell_s', p.s(p.crossing_index), ...
    'gap_lower_frequency_khz', p.gap_lower_rad_s/(2*pi*1e3), ...
    'gap_upper_frequency_khz', p.gap_upper_rad_s/(2*pi*1e3), ...
    'axis_boundary_condition', 'zero radial flux (homogeneous Neumann)', ...
    'edge_boundary_condition', 'zero face value (homogeneous Dirichlet)', ...
    'normalization', 'integral_0^1 (xi_m^2 + xi_mplus1^2) ds = 1', ...
    'matlab_solver', 'eigs, smallest-real eigenpairs');
fid = fopen(fullfile(outputDir, 'metadata.json'), 'w');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', jsonencode(metadata, 'PrettyPrint', true));
end
